server:
  port: 8080

spring:
  datasource:
    username: root
    password: shehap
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

security:
  jwt:
    secret-key: e7b28455b34066c560ce20f30bb31b47bacafa98331ef8d054ca9c21be5c7481
    expire-length: 900000  #15min